### ISSUE TITLE
Laptop doesn't support 'power.draw', 'power.limit'

### ISSUE THREAD

**Issue by lpfy** [yangheng95/autocuda#1]
`numberic_args = ['memory.free', 'memory.total', 'power.draw', 'power.limit']  # 可计数的参数`
`power_manage_enable = lambda v: (not 'Not Support' in v)  # lambda表达式，显卡是否滋瓷power management（笔记本可能不滋瓷）`

my laptop's nvidia-smi command return 'N/A' rather than 'Not Support' for 'power.draw', 'power.limit', so probably it's better to change lambda v to filter out N/A as well

**Comment by yangheng95** [comment]
Can you test it and PR to fix it? Because I dont have a laptop having a cuda.

**Comment by lpfy** [comment]
Thanks for accepted/merged my Pull Request

**Comment by yangheng95** [comment]
Thanks very much for your fix patch, I upload 0.9 version based on this commit, you can install and test.
